# 문제 1: 파이썬 데이터파트 (총 30점)

문제구성:
1-1(1) 몫에 대한 연산
1-1(2) 나머지 연산
1-1(3) 몫과 나머지 같이 출력
1-2(1) 문자열
1-2(2) 시작 인덱스 찾기
1-2(3) 문자열 변경
1-3(1) 리스트 이해
1-3(2) 오류 원인 찾기

### 1-1번 문제 (6점): 변수와 연산자 활용

두 정수 `a = 15`와 `b = 7`이 주어졌습니다. 다음 지시에 따라 코드를 작성하세요.

1-1(1) (3점): `a`를 `b`로 나눈 **몫**을 계산하여 변수 `quotient`에 저장하는 코드를 작성하세요.

1-1(2) (3점): `a`를 `b`로 나눈 **나머지**를 계산하여 변수 `remainder`에 저장하는 코드를 작성하세요.

1-1(3) (4점): 계산된 `quotient`와 `remainder` 값을 주어진 출력 예시와 같이 포맷하여 출력하는 코드를 작성하세요.

#### 1-1번 문제 정답 (코드 및 출력)

```python
a = 15
b = 7

quotient = a // b
remainder = a % b

print(f"몫: {quotient}")
print(f"나머지: {remainder}")
```

**출력 결과:**
```
몫: 2
나머지: 1
```

### 1-2번 문제 (6점): 문자열 다루기

주어진 문자열 `s = "Python is fun and powerful"`에서 다음 작업을 수행하세요.

1.  문자열 `s`의 길이를 출력하세요.(3점)
2.  `"fun"`이라는 단어가 시작되는 인덱스를 찾아서 출력하세요.(3점)
3.  문자열 `s`에서 `"Python"`을 `"Euron"`로 변경한 새 문자열을 출력하세요.(4점)

```
문자열 길이: 25
'fun' 시작 인덱스: 10
변환된 문자열: Euron is fun and powerful
```

In [ ]:
s = "Python is fun and powerful"

# 1. 문자열 길이 출력
print(f"문자열 길이: {len(s)}")

# 2. 'fun' 단어 시작 인덱스 찾기
fun_index = s.find("fun")
print(f"'fun' 시작 인덱스: {fun_index}")

# 3. 문자열 'Python'을 'Java'로 변경
new_s = s.replace("Python", "Java")
print(f"변환된 문자열: {new_s}")

### 1-3번 문제 (8점): 리스트 조작
(1) (5점)

숫자들을 담고 있는 리스트 `numbers = [10, 20, 30, 40, 50]`가 주어졌습니다.

1.  리스트의 첫 번째 요소를 출력하세요.
2.  리스트의 마지막에 `60`을 추가하고, 변경된 리스트를 출력하세요.


```
첫 번째 요소: 10
변경된 리스트 (추가 후): [10, 20, 30, 40, 50, 60]

```
(2) (5점)

다음 코드에서 오류가 발생하였다. 원인을 설명해보아라.

**오류가 발생하는 코드:**
```python
my_list = [10, 20]
my_list[2] = 30
print(my_list)
```

해답

In [ ]:
numbers = [10, 20, 30, 40, 50]

# 1-3(1): 리스트의 첫 번째 요소를 출력하고, 마지막에 60을 추가 후 변경된 리스트 출력
print(f"첫 번째 요소: {numbers[0]}")
numbers.append(60)
print(f"변경된 리스트 (추가 후): {numbers}")

**오류 원인 설명:**

파이썬 리스트는 0부터 시작하는 인덱스를 가집니다. `my_list = [10, 20]`는 두 개의 요소를 가지고 있으며, 유효한 인덱스는 `0`과 `1`입니다.

`my_list[2] = 30`는 존재하지 않는 인덱스 `2`에 값을 할당하려고 시도하기 때문에 `IndexError: list assignment index out of range` 오류가 발생합니다.

새 요소를 리스트에 추가하려면 `append()` 메서드를 사용해야 합니다 (예: `my_list.append(30)`).

### **1-4. 제시문에 따라 문제에 대한 답을 제시하고 해결해주세요. (10점)**
- 다음과 같이 학생별 각 과목의 점수가 담긴 이차원 데이터가 주어졌습니다.

  \begin{array}{|c|c|c|c|}
  \hline
  \text{번호} & \text{국어} & \text{영어} & \text{수학} \\
  \hline
  1 & 60 & 85 & 50 \\
  2 & 20 & 40 & 30 \\
  3 & 100 & 80 & 95 \\
  \hline
  \end{array}

- 이 문제의 목표는 학생별 총점과 각 과목의 최고점을 계산하는 것입니다.

#### **1-4-1. 주관식 질문 (2점)**
- 화연이는 데이터를 이차원 리스트로 저장하기 위해 다음과 같은 파이썬 코드를 작성했습니다.
  ```
  # 점수 데이터가 담긴 이차원 리스트
  scores = [
      ["60", "85", "50"],
      ["20", "40", "30"],
      ["100", "80", "95"]
  ]
  ```

- 화연이의 코드에서는 `scores` 데이터가 **점수 계산에 적합하지 않은 형태로** 저장되어 있습니다.

❓ **그 이유는 무엇일까요? 이 문제를 해결하려면 어떻게 해야 하는지 해결 방법을 간략하게 설명해주세요.**

- **예시 답안**

주어진 데이터는 점수가 숫자가 아닌 `문자열`로 저장되어 있습니다.

이를 해결하기 위해서는 `정수형`으로 `형변환`한 후에 계산을 진행해야 합니다.

#### **1-4-2. 코드 작성 (8점)**

- 각 학생별 총점을 계산해주세요.
  - **🔍힌트:** 각 학생의 점수는 가로 방향(=한 행)에 나열되어 있습니다.
- 과목별 최고점을 계산해주세요.
  - **🔍힌트:** 각 과목의 점수는 세로 방향(=각 열)에 나열되어 있습니다.

**💚 Test Case**  

- 출력
```
학생별 총점: [195, 90, 275]
과목별 최고점: [100, 85, 95]
```

In [ ]:
### 예시 답안
# 점수 데이터가 담긴 이차원 리스트
scores = [
    ["60", "85", "50"],
    ["20", "40", "30"],
    ["100", "80", "95"]
]

# 1-4-1번의 문제를 해결하여 scores 이차원 리스트를 재정의한 scores_new 생성하기
## 코드로 구현하면 2점, 직접 int로 리스트 만들면 1점
scores_new = [list(map(int, student_scores)) for student_scores in scores]

# 학생별 총점을 구하고 total_scores 리스트에 저장하기
total_scores = [sum(student) for student in scores_new]

print(f"학생별 총점: {total_scores}")

# 과목별 최고점을 구하고 max_scores 리스트에 저장하기
max_scores = []
for i in range(len(scores_new[0])):
  max_scores.append(max(score[i] for score in scores_new))
# max_scores = [max(subject) for subject in zip(*scores_new)]

print(f"과목별 최고점: {max_scores}")

학생별 총점: [195, 90, 275]
과목별 최고점: [100, 85, 95]

# **2️⃣ 문제 2**
- 출제 의도
  - 파이썬의 세 가지 자료구조와 함수에 대한 이해 확인

- 평가 기준
  - 2-1번. 반복문으로 구성된 함수 만들기
  - 2-2번. 딕셔너리에 대한 이해 확인
  - 2-3번. 파이썬의 자료구조 세 가지 정보 확인
  - 2-4번. 딕셔너리로 함수 생성

---

## **2-1. 제시문에 따라 문제를 해결해주세요. (6점)**
- 반복문을 이용해 주어진 리스트들의 합을 구하는 함수를 만드세요

- 이때 함수의 이름은 calcsum( )입니다. [3점]

- 위에서 구한 calcsum( )을 이용해 평균을 구하세요.

- 이때 평균에 대한 함수 이름은 calcavg( )입니다. [3점]


-주어진 리스트 : ex_list = [-6, 3, 2, 41, 15, 35, 23, -3]

In [ ]:
### 답안

# calcsum( )함수 생성 (3점)
def calcsum(inputlist):
  sum = 0

  for i in inputlist:
    sum = sum + i

  return sum

# calcavg( )함수 생성 (4점)
def calcavg(inputlist):
  avg = None

  sum = calcsum(inputlist)

  if len(inputlist) > 0 :
    avg = sum / len(inputlist)
  else :
    avg = None

  return avg

ex_list = [-6, 3, 2, 41, 15, 35, 23, -3]

# 결과 출력
print("주어진 리스트의 합:\n", calcsum(ex_list))
print("\n주어진 리스트의 평균:\n", calcavg(ex_list))

주어진 리스트의 합:
 110

주어진 리스트의 평균:
 13.75

## 2-2. 제시문에 따라 문제를 해결해주세요. (10점)

- 아래의 정보를 파이썬의 딕셔너리 형태로 나타내고, 생성한 딕셔너리를 화면에 출력하세요. [4점]

  - '빵' : 슈크림, 마카롱, 케이크
  - '면' : 신라면, 진짬뽕, 짜장면
  - '음료' : 콜라, 사이다, 사과주스, 환타
  - '밥' : 비빔밥, 순대국밥


- 이렇게 만들어진 딕셔너리에서 '면'에 해당하는 것들만 출력하세요. [3점]

- '밥' 카테고리에 있는 순대국밥을 삭제하고, '음료' 카테고리에 포도주스를 추가한 뒤 그 결과를 화면에 출력하세요. [각 1.5점]

📌 **조건**
- '면'에 해당하는 것들 추출과정에서 함수를 사용해야함

  - 딕셔너리이름['면']은 사용 불가

- 포도주스 추가 과정에서 리스트 이어붙이기 사용 불가 (사용 시 0점 처리)

**💚 Test Case**  

- 출력
```
{'빵': ['슈크림', '마카롱', '케이크'], '면': ['신라면', '진짬뽕', '짜장면'], '음료': ['콜라', '사이다', '사과주스', '환타'], '밥': ['비빔밥', '순대국밥']}
['신라면', '진짬뽕', '짜장면']
['신라면', '진짬뽕', '짜장면']
{'빵': ['슈크림', '마카롱', '케이크'], '면': ['신라면', '진짬뽕', '짜장면'], '음료': ['콜라', '사이다', '사과주스', '환타', '포도주스'], '밥': ['비빔밥']}
```

In [ ]:
### 예시 답안 ###
# 딕셔너리 입력

product = {'빵': ['슈크림', '마카롱', '케이크'], '면' : ['신라면', '진짬뽕', '짜장면'], '음료' : ['콜라', '사이다', '사과주스', '환타'], '밥' : ['비빔밥', '순대국밥']}
## 딕셔너리는 { }를 이용해서 표시한다. 이때 value의 값이 여러 개면 [ ]를 통해 표시

print(product)

#딕셔너리에서 '면'에 해당하는 value들만 출력하기
print(product.get('면'))

#'밥' 카레고리에 있는 순대국밥을 삭제
product['밥'].remove('순대국밥')

# product['밥'].pop(1) 이 형태도 가능

#'음료' 카테고리에 포도주스를 추가
product['음료'].append('포도주스')

#최종 결과 출력
print(product)

{'빵': ['슈크림', '마카롱', '케이크'], '면': ['신라면', '진짬뽕', '짜장면'], '음료': ['콜라', '사이다', '사과주스', '환타'], '밥': ['비빔밥', '순대국밥']}
['신라면', '진짬뽕', '짜장면']
['신라면', '진짬뽕', '짜장면']
{'빵': ['슈크림', '마카롱', '케이크'], '면': ['신라면', '진짬뽕', '짜장면'], '음료': ['콜라', '사이다', '사과주스', '환타', '포도주스'], '밥': ['비빔밥']}

##2-3. 주관식 질문 (4점)

파이썬의 자료 구조 세 가지인 리스트, 딕셔너리, 튜플에 대한 특징을 각각 1가지씩 말해주세요.

- 예시답안

리스트 : [ ]를 사용해 표현, 순서를 가지고 있고 인덱스를 사용한다, 저장된 값을 쉽게 수정할 수 있다

딕셔너리 : 순서가 없는 자료형, key : value의 형태로 저장, key를 통해 value를 얻는다, { }를 사용해 표현

튜플 : 한번 저장된 값은 수정할 수 없다, 읽기 전용의 데이터를 저장할 때 유용하게 사용한다, ( )를 사용

## 2-4. 제시문에 따라 문제에 대한 답을 제시하고 해결해주세요. (10점)

- 아래와 같이 문자열이 하나 주어졌습니다.

> sentence = " apple banana apple orange banana apple"


- 문자열을 공백 기준으로 나눈 후 각 단어의 등장 횟수를 딕셔너리로 반환 (4점)
  - 위 함수의 이름을 count_words(sentence)라고 한다.


- 가장 많이 등장한 단어를 반환하는 함수 만들기(3점)
  - 위 함수의 이름은 most_common(word_dict)이다. 이때, 반환값은 하나이다.

- 특정 단어가 몇 번 등장했는지 반환하는 함수 만들기(3점)
  -위 함수의 이름은 count_word(word_dict, word)이다. 없으면 0 반환.

**💚 Test Case**  
  
[예시]
- 입력
```
word_dict = count_words(sentence)

print(word_dict)

print(most_common(word_dict))

print(count_word(word_dict, "apple"))
```

- 출력
```
{'apple' :3, 'banana':2, 'orange' : 1}
apple
3
```

In [ ]:
### 예시 답안

sentence = "apple banana apple orange banana apple"

# split( )을 이용해 공백을 없애고, 각 단어의 등장 횟수를 딕셔너리로 반환하는 함수 생성
def count_words(sentence) :
  words = sentence.split()

  word_dict = {}

  for word in words :
    if word in word_dict :
      word_dict[word] = word_dict[word] + 1
    else :
      word_dict[word] = 1

  return word_dict

# 가장 많이 등장한 단어를 반환하는 함수 생성
def most_common(word_dict) :
  max_count = 0
  max_word = ""

  for word in word_dict :
    if word_dict[word] > max_count :
      max_count = word_dict[word]
      max_word = word

  return max_word

#특정 단어가 몇 번 등장했는지 확인하는 함수 생성
def count_word(word_dict, word) :
  if word in word_dict :
    return word_dict[word]
  else :
    return 0

#실행
word_dict = count_words(sentence)

print(word_dict)

print(most_common(word_dict))

print(count_word(word_dict, "apple"))

{'apple': 3, 'banana': 2, 'orange': 1}
apple
3

# **3️⃣ Part 3 (40점)**
- Part 3은 기본적인 **함수 및 자료구조**와 관련된 문제들입니다.
  - 주어진 조건에 따라 해당 작업을 수행하는 프로그램을 작성해 주세요.
- ```변수명```이나 ```리스트명``` 등 문제에서 이미 설정된 부분들은 수정하시면 **안됩니다**.
  - 문제 설정 부분은 미리 코드가 작성되어 있는데, 해당 부분을 수정하시면 안 된다는 의미입니다.  
  (수정 시 경우에 따라 **0점 처리**됨을 주의해 주시기 바랍니다.)
  - 주어진 코드를 활용하여 프로그램을 완성해 주시면 됩니다.

---

## 문제 3-1 (총 20점)

-출제 의도

파이썬 기초 문법(문자열 슬라이싱, 인덱스 접근, 조건문, 출력 형식, 함수)을 종합하여 알고리즘 작성 역량을 평가한다.

-기타 설명

입력한 주민등록번호로 출생년도, 출생월, 출생일 및 성별을 출력하는 프로그램을 단계별로 완성한다.

주민등록번호는 반드시 -를 포함하여 입력된다. (예: 781201-1273845)

### 3-1-1. 기본 문자열 자르기.(5점)
주민등록번호를 입력받아, 아래 정보를 각각 추출해 출력하시오.


*   출생년도(앞 2자리)
*   출생월(3~4자리)
*   출생일(5~6자리)




📌 조건

*   문자열 슬라이싱만 사용 (조건문 불필요)
*   출력은 YY MM DD 형식으로 공백으로 구분

💚 Test Case



*   입력

    781201-1273845
*   출력
    
    78 12 01

In [ ]:
#입력 받기
jumin = input()

###답안 작성###
yy = jumin[0:2]
mm = jumin[2:4]
dd = jumin[4:6]

print(yy, mm, dd)

###3-1-2. 인덱스 접근 + 조건문(5점)
주민등록번호에서 - 뒤 첫 번째 숫자를 읽어 성별을 출력하시오.


*   1 또는 3 → 남자 M
*   2 또는 4 → 여자 F

📌 조건


*   인덱스 접근으로 성별코드 추출
*   if / elif / else 사용

💚 Test Case


*   입력

    781201-1273845
*   출력
    
    M

In [ ]:
#입력 받기
jumin = input()

###답안 작성###
code = jumin[7]

if code == '1' or code == '3':
    print('M')
else:
    print('F')

### 3-1-3. 문자열 + 조건문 + 출력 형식 (6점)
주민등록번호를 입력받아 다음 형식으로 출력하시오.


*   출생년도는 4자리로 출력
     *   성별 코드가 1,2면 19YY
     *   성별 코드가 3,4면 20YY


*   성별은
     *   1,3 → M
     *   2,4 → W

📌 출력 형식


*   YYYY/MM/DD 뒤에 공백 1칸 후 M 또는 F
*   예: 1978/12/01 M

💚 Test Case


*   입력

    781201-1273845
*   출력

    1978/12/01 M

In [ ]:
#입력받기
jumin = input()

###답안 작성###
jumin = input().strip()

yy = jumin[0:2]
mm = jumin[2:4]
dd = jumin[4:6]
code = jumin[7]

if code == '1' or code == '2':
    year = '19' + yy
else:
    year = '20' + yy

if code == '1' or code == '3':
    gender = 'M'
else:
    gender = 'F'

print(f"{year}/{mm}/{dd} {gender}")

### 3-1-4. 설명(4점)
아래 항목을 간단히 서술하시오.(각 1점)


1.   출생년도/월/일을 추출하기 위해 사용한 방법
2.   성별코드의 위치(인덱스)와 그 이유
3.   1900년대/2000년대 출생을 구분하는 기준
4.   최종 출력 형식을 맞춘 방법

답안 작성


> 주민등록번호 문자열에서 슬라이싱으로 YYMMDD를 잘라냈다.
  '-' 다음 첫 숫자가 성별코드이므로 인덱스 7을 사용했다.
 성별코드가 1,2면 1900년대(19YY), 3,4면 2000년대(20YY)로 처리했다.
f-string을 사용해 YYYY/MM/DD 형태로 만들고 공백 후 성별을 출력했다.

##문제 3-2 (10점)
-출제 의도


*   자료구조 배열(list) 활용 능력 평가
*   인덱스 기반 탐색 알고리즘 구현
*   반복문 + 조건문을 이용한 Two Sum 문제 해결

정수 배열 nums와 정수 target을 입력받아,
배열에서 두 수의 합이 target이 되는 두 인덱스를 출력하시오.

정답은 순서 상관없이 출력 가능하다.

📌 입력 형식


1.   첫 줄: 배열 요소 (공백으로 구분된 정수)
2.   둘째 줄: target 값

     예)

     2 7 11 15

     9

📌 출력 형식

    [0, 1]  (설명: nums[0] + nums[1] = 9)

💚 Test Case

예시1)

Input: nums = [3,2,4], target = 6

Output: [1,2]

예시2)

Input: nums = [3,3], target = 6

Output: [0,1]

📌 조건



*   같은 인덱스 두 번 사용 금지
*   반드시 하나의 정답만 존재
*   배열 길이: 2 이상
*   for 반복문 사용
*   리스트 인데스 접근 사용

In [ ]:
###답안 작성###
nums = list(map(int, input().split()))
target = int(input())

for i in range(len(nums)):
    for j in range(i + 1, len(nums)):
        if nums[i] + nums[j] == target:
            print([i, j])

##문제 3-3. Counting + Sort 활용 문제 (10점)
-출제 의도


*   자료구조 **리스트(List)** 활용 능력 평가
*   Counting 개념 이해
*   정렬(sort)을 활용한 알고리즘 설계 능력 평가
*   반복문과 조건문을 통한 비교 연산 구현

정수 배열 nums가 주어질 때,
각 원소에 대해 자신보다 작은 수의 개수를 계산하여 리스트로 반환하시오.

조건:


*   j != i
*   nums[j] < nums[i]

📌 함수 형식 (반드시 유지)


```
def smallerNumbersThanCurrent(self, nums):
    """
    :type nums: List[int]
    :rtype: List[int]
    """
```
반환값: 각 위치별 작은 수의 개수를 담은 리스트

💚 Test Case

예시1)

Input: nums = [8,1,2,2,3]

Output: [4,0,1,1,3] (8보다 작은 수: 4개, 1보다 작은 수: 0개, 2보다 작은 수: 1개, 3보다 작은 수: 3개)

예시2)

Input: nums = [6,5,4,8]

Output: [2,1,0,3]

📌 제약 조건


*   2 ≤ nums.length ≤ 500
*   0 ≤ nums[i] ≤ 100|

In [ ]:
###답안작성###
def smallerNumbersThanCurrent(self, nums):
        sorted_nums = sorted(nums)
        result = []

        for num in nums:
            count = sorted_nums.index(num)
            result.append(count)

        return result
print(smallerNumbersThanCurrent(nums))

# **4️⃣ Part 4 (10점)**
- Part 4는 ML세션에서 다룰 **판다스, 넘파이**와 관련된 기본적인 문제들입니다.
- 앞 공지에서 말씀드렸듯, 이 문제의 점수가 1차 통과의 당락을 결정하진 않습니다. 교재, 구글링, ChatGPT, 지인 찬스 등을 통해 최대한 풀어 제출해 주시면 됩니다.
- 주어진 조건에 따라 해당 작업을 수행하는 코드를 작성해주세요.
---

## **4-1. 넘파이(5점)**
- 주어진 배열에서 모든 요소의 평균값을 구하는 코드를 작성하세요.

  - 배열 요소들은 9, 7, 1.4, 5.3423, 4.29입니다.
  - 이를 `numpy` 배열로 정의하여 평균을 계산하세요.

**📌 조건**  
- `numpy` 내장 함수를 활용해 주세요.
- 배열은 `arr`라는 변수에 직접 정의해 주세요.
  - `arr` 변수의 type은 `numpy.ndarray`여야 합니다.
- 배열의 평균값을 계산한 후 출력해주세요.
- 배열 내 원소들의 형식을 str형식으로 변환해 주세요.

In [ ]:
import numpy as np  # 넘파이 모듈 호출

# 배열 정의
elements = [9, 7, 1.4, 5.3423, 4.29]
arr = np.array(elements)  ###답안###

# 평균값 계산
mean_value = np.mean(arr)  ###답안###
print(mean_value)

# 배열내 원소들의 형식을 str형식으로 변환
arr = arr.astype("str") ###답안###
print(arr)

5.40646
['9.0' '7.0' '1.4' '5.3423' '4.29']

## **4-2. 판다스(5점)**
### **제시문에 따라 문제를 해결해 주세요.**
- 우선 판다스 모듈을 import하고, 데이터 분석에 활용할 데이터 프레임을 생성하겠습니다.

In [ ]:
### 실행해 주세요!

# 판다스 모듈 호출
import pandas as pd

data = {
    "모델명": ["소나타", "아반떼", "그랜저", "쏘렌토", "카니발", "스포티지", "K5", "K7", "모닝", "GV80"],
    "브랜드": ["현대", "현대", "현대", "기아", "기아", "기아", "기아", "기아", "기아", "제네시스"],
    "가격(만원)": [2500, 1800, 3800, 3500, 4000, 3000, 2700, 3500, 1200, 6000],
    "판매량": [500, 800, 400, 450, 300, 350, 420, 200, 600, 150]
}

# 데이터프레임 생성
df = pd.DataFrame(data)
df

    모델명   브랜드  가격(만원)  판매량
0   소나타    현대    2500  500
1   아반떼    현대    1800  800
2   그랜저    현대    3800  400
3   쏘렌토    기아    3500  450
4   카니발    기아    4000  300
5  스포티지    기아    3000  350
6    K5    기아    2700  420
7    K7    기아    3500  200
8    모닝    기아    1200  600
9  GV80  제네시스    6000  150

### **4-2-1. 브랜드별 데이터의 개수를 구해주세요.(2점)**
**🔍 힌트**
- 판다스에는 데이터의 특정 열(column)에 있는 값들의 개수를 세는 방법이 있어요.

In [ ]:
df['브랜드'].value_counts()

브랜드
기아      6
현대      3
제네시스    1
Name: count, dtype: int64

### **4-2-2. 각 상품의 총 매출액(가격(만원)× 판매량)을 계산하여 새로운 `총매출(만원)` 열을 추가해 주세요.(3점)**

In [ ]:
df["총매출(만원)"] = df["가격(만원)"] * df["판매량"]

# 결과 8확인
df

    모델명   브랜드  가격(만원)  판매량  총매출(만원)
0   소나타    현대    2500  500  1250000
1   아반떼    현대    1800  800  1440000
2   그랜저    현대    3800  400  1520000
3   쏘렌토    기아    3500  450  1575000
4   카니발    기아    4000  300  1200000
5  스포티지    기아    3000  350  1050000
6    K5    기아    2700  420  1134000
7    K7    기아    3500  200   700000
8    모닝    기아    1200  600   720000
9  GV80  제네시스    6000  150   900000